[skip ci] In developer CI, QA wait for needed builds only, not all

diff --git a/.github/workflows/developer_ci.yml b/.github/workflows/developer_ci.yml
--- a/.github/workflows/developer_ci.yml
+++ b/.github/workflows/developer_ci.yml
@@ -39,7 +39,7 @@ jobs:
             exit 1
           fi
 
-  build:
+  build-for-qa:
     needs: guard
     if: ${{ github.repository_owner == 'OpenRadioss' }}
     # concurrency: 
@@ -63,18 +63,98 @@ jobs:
             binary: starter
             image_name: build-linux64_gf:cos8-ompi411-devts11
 
-          - build: starter_linux64_gf_sp 
-            precision: sp
-            os: linux64
-            binary: starter
-            image_name: linux64-cos10-bld:ompi4.1.1-ts15
-
           - build: engine_linux64_gf_ompi
             precision: dp
             os: linux64
             binary: engine
             mpi: ompi
             image_name: build-linux64_gf:cos8-ompi411-devts11
+
+    container: 
+      image: "fr-qafactorydev.europe.altair.com/${{ matrix.image_name }}"
+      volumes: 
+        - /etc/localtime:/etc/localtime:ro
+
+    steps:
+
+      - name: Clean local exe dir
+        run: |
+          rm -rf exec
+          md5sum exec/* || echo "Nothing in exec/" 
+
+      # Get last git modifications, WS is not persistent here
+      - uses: actions/checkout@v4
+        with:
+          lfs: 'false'
+          ref: refs/pull/${{ github.event.number }}/merge
+
+      - name: Running build
+        run: |
+          echo "Running using ref: refs/pull/${{ github.event.number }}/merge"
+          
+          mpi_opts=''
+          if [ ! -z ${{ matrix.mpi }} ]
+          then
+            mpi_opts="-mpi=${{ matrix.mpi }}"
+          fi
+
+          cmd="./build_script.sh -release -arch=${{ matrix.os }}_gf -prec=${{ matrix.precision }} -nt=${{ env.BUILD_NB_THREAD }} -static-link $mpi_opts"
+          echo "========================================="
+          echo "--  BUILD ${{ matrix.build }} --"   
+          echo "--  $cmd --"   
+          echo "========================================="
+          source /home/adminqa/.bashrc
+          chmod 755 Compiling_tools/script/*
+          chmod 755 ${{ matrix.binary }}/build_script.sh
+
+          md5sum exec/* || echo "Nothing in exec/" 
+          mkdir exec
+          cd ${{ matrix.binary }}
+
+          eval $cmd
+
+          cd ..
+          md5sum exec/* || exit 1
+
+      # Upload artifact (since V4 we can't upload artifact using the same name, each one must be unique) 
+      - name: Upload built artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: bins-${{ matrix.os }}-${{ matrix.precision }}-${{ matrix.build }}
+          path: exec
+
+      # We upload extlib only once, arbitrary choice
+      - name: Upload extlib artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: extlib.zip
+          path: extlib.zip
+        if: ${{ matrix.build == 'starter_linux64_gf' }}
+
+  build:
+    needs: guard
+    if: ${{ github.repository_owner == 'OpenRadioss' }}
+    # concurrency: 
+    #   group: ${{ github.ref_name }}
+    #   cancel-in-progress: true
+
+    # DEV ONLY # runs-on: ["build","dev","dev_ci"]
+    runs-on: ["build","developer_ci"]
+
+    env:
+      BUILD_NB_THREAD: 2
+
+    strategy:
+      # If one job fails othere are canceled
+      fail-fast: true
+      matrix:
+        include:
+
+          - build: starter_linux64_gf_sp 
+            precision: sp
+            os: linux64
+            binary: starter
+            image_name: linux64-cos10-bld:ompi4.1.1-ts15
 
           - build: engine_linux64_gf_ompi_sp
             precision: sp
@@ -148,14 +228,6 @@ jobs:
         with:
           name: bins-${{ matrix.os }}-${{ matrix.precision }}-${{ matrix.build }}
           path: exec
-
-      # We upload extlib only once, arbitrary choice
-      - name: Upload extlib artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: extlib.zip
-          path: extlib.zip
-        if: ${{ matrix.build == 'starter_linux64_gf' }}
 
   code-analysis:
     needs: guard
@@ -233,7 +305,7 @@ jobs:
           eval $cmd
 
   qa:
-    needs: build
+    needs: build-for-qa
     # DEV ONLY # runs-on: ["qa_${{ matrix.os }}","dev"]
     runs-on: ["qa_${{ matrix.os }}","developer_ci"]
     container: 
