[skip ci] Add GNU static code analysis in developer CI

diff --git a/.github/workflows/developer_ci.yml b/.github/workflows/developer_ci.yml
--- a/.github/workflows/developer_ci.yml
+++ b/.github/workflows/developer_ci.yml
@@ -127,6 +127,84 @@ jobs:
           name: extlib.zip
           path: extlib.zip
         if: ${{ matrix.build == 'starter_linux64_gf' }}
+
+  code-analysis:
+    # We execute after all builds (in // with QA)
+    if: ${{ github.repository_owner == 'OpenRadioss' }}
+
+    # DEV ONLY # runs-on: ["build","dev_devci"]
+    runs-on: ["build","developer_ci"]
+    container: 
+      image: fr-qafactorydev.europe.altair.com/build-linux64_gf:cos8-ompi411-devts11
+      credentials: 
+        username: ${{secrets.DOCKER_REGISTRY_USER}}
+        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
+      volumes: 
+        - /etc/localtime:/etc/localtime:ro
+
+    env:
+      BUILD_NB_THREAD: 2
+
+    strategy:
+      # If one job fails othere are canceled
+      fail-fast: true
+      matrix:
+        include:
+          - build: starter_linux64_gf
+            precision: dp
+            os: linux64
+            binary: starter
+          - build: engine_linux64_gf_ompi
+            precision: dp
+            os: linux64
+            binary: engine
+            mpi: ompi
+
+    steps:
+
+      - name: Clean local exe dir
+        run: |
+          rm -rf exec
+          md5sum exec/* || echo "Nothing in exec/" 
+
+      # Get last git modifications, WS is not persistent here
+      - uses: actions/checkout@v4
+        with:
+          lfs: 'true'
+          ref: refs/pull/${{ github.event.number }}/merge
+
+      - name: Generate Fortran Signatures
+        run: |
+          source /home/adminqa/.bashrc
+          cd scripts/gcc_plugin
+          sh build.sh          
+          cd -
+
+      - name: Running build with code analysis
+        run: |
+          echo "Running using ref: refs/pull/${{ github.event.number }}/merge"
+          
+          mpi_opts=''
+          if [ ! -z ${{ matrix.mpi }} ]
+          then
+            mpi_opts="-mpi=${{ matrix.mpi }}"
+          fi
+
+          cmd="./build_script.sh -debug=analysis -arch=${{ matrix.os }}_gf -prec=${{ matrix.precision }} -nt=${{ env.BUILD_NB_THREAD }} -static-link $mpi_opts"
+          echo "========================================="
+          echo "--  BUILD & ANALYSE ${{ matrix.build }} --"   
+          echo "--  $cmd --"   
+          echo "========================================="
+          source /home/adminqa/.bashrc
+          chmod 755 Compiling_tools/script/*
+          chmod 755 ${{ matrix.binary }}/build_script.sh
+
+          md5sum exec/* || echo "Nothing in exec/" 
+          mkdir exec
+          cd ${{ matrix.binary }}
+
+          eval $cmd
+
   qa:
     needs: build
     # DEV ONLY # runs-on: ["qa_${{ matrix.os }}","dev"]
